### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by 984958198** [TurboGears/tg2#65] opened 2015-07-16 06:18 UTC
'gearbox serve --daemon' will stuck when start it for a moment 
'gearbox serve --status' seems well,but get no response after a call

**Comment by amol-** [comment] 2015-07-16 06:36
duplicate of https://github.com/TurboGears/gearbox/issues/5

Already investigating the issue.

**Closed by amol-** 2015-07-16 06:36 UTC
